# Generated by Django 4.2.7 on 2023-11-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('autor', models.CharField(blank=True, max_length=255, null=True, verbose_name='автор')),
                ('publishing_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='год публикации')),
                ('isbn', models.CharField(blank=True, max_length=17, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-name'],
            },
        ),
    ]
